// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/tnet/grpc/proto/transport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamData represents data being sent over the stream
type StreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      int32                  `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Close         bool                   `protobuf:"varint,3,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_internal_tnet_grpc_proto_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tnet_grpc_proto_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_internal_tnet_grpc_proto_transport_proto_rawDescGZIP(), []int{0}
}

func (x *StreamData) GetStreamId() int32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

// PingRequest is sent to test connection
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_tnet_grpc_proto_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tnet_grpc_proto_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_tnet_grpc_proto_transport_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PongResponse is returned from ping
type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_internal_tnet_grpc_proto_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tnet_grpc_proto_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_internal_tnet_grpc_proto_transport_proto_rawDescGZIP(), []int{2}
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_tnet_grpc_proto_transport_proto protoreflect.FileDescriptor

const file_internal_tnet_grpc_proto_transport_proto_rawDesc = "" +
	"\n" +
	"(internal/tnet/grpc/proto/transport.proto\x12\x05paqet\"S\n" +
	"\n" +
	"StreamData\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x05R\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05close\x18\x03 \x01(\bR\x05close\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\",\n" +
	"\fPongResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2u\n" +
	"\x0ePaqetTransport\x122\n" +
	"\x06Stream\x12\x11.paqet.StreamData\x1a\x11.paqet.StreamData(\x010\x01\x12/\n" +
	"\x04Ping\x12\x12.paqet.PingRequest\x1a\x13.paqet.PongResponseB Z\x1epaqet/internal/tnet/grpc/protob\x06proto3"

var (
	file_internal_tnet_grpc_proto_transport_proto_rawDescOnce sync.Once
	file_internal_tnet_grpc_proto_transport_proto_rawDescData []byte
)

func file_internal_tnet_grpc_proto_transport_proto_rawDescGZIP() []byte {
	file_internal_tnet_grpc_proto_transport_proto_rawDescOnce.Do(func() {
		file_internal_tnet_grpc_proto_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_tnet_grpc_proto_transport_proto_rawDesc), len(file_internal_tnet_grpc_proto_transport_proto_rawDesc)))
	})
	return file_internal_tnet_grpc_proto_transport_proto_rawDescData
}

var file_internal_tnet_grpc_proto_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_tnet_grpc_proto_transport_proto_goTypes = []any{
	(*StreamData)(nil),   // 0: paqet.StreamData
	(*PingRequest)(nil),  // 1: paqet.PingRequest
	(*PongResponse)(nil), // 2: paqet.PongResponse
}
var file_internal_tnet_grpc_proto_transport_proto_depIdxs = []int32{
	0, // 0: paqet.PaqetTransport.Stream:input_type -> paqet.StreamData
	1, // 1: paqet.PaqetTransport.Ping:input_type -> paqet.PingRequest
	0, // 2: paqet.PaqetTransport.Stream:output_type -> paqet.StreamData
	2, // 3: paqet.PaqetTransport.Ping:output_type -> paqet.PongResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_tnet_grpc_proto_transport_proto_init() }
func file_internal_tnet_grpc_proto_transport_proto_init() {
	if File_internal_tnet_grpc_proto_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_tnet_grpc_proto_transport_proto_rawDesc), len(file_internal_tnet_grpc_proto_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_tnet_grpc_proto_transport_proto_goTypes,
		DependencyIndexes: file_internal_tnet_grpc_proto_transport_proto_depIdxs,
		MessageInfos:      file_internal_tnet_grpc_proto_transport_proto_msgTypes,
	}.Build()
	File_internal_tnet_grpc_proto_transport_proto = out.File
	file_internal_tnet_grpc_proto_transport_proto_goTypes = nil
	file_internal_tnet_grpc_proto_transport_proto_depIdxs = nil
}
