// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/tnet/grpc/proto/transport.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaqetTransport_Stream_FullMethodName = "/paqet.PaqetTransport/Stream"
	PaqetTransport_Ping_FullMethodName   = "/paqet.PaqetTransport/Ping"
)

// PaqetTransportClient is the client API for PaqetTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaqetTransport service for bidirectional streaming
type PaqetTransportClient interface {
	// Stream opens a bidirectional stream for data transfer
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamData, StreamData], error)
	// Ping tests the connection
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type paqetTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewPaqetTransportClient(cc grpc.ClientConnInterface) PaqetTransportClient {
	return &paqetTransportClient{cc}
}

func (c *paqetTransportClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamData, StreamData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaqetTransport_ServiceDesc.Streams[0], PaqetTransport_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamData, StreamData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaqetTransport_StreamClient = grpc.BidiStreamingClient[StreamData, StreamData]

func (c *paqetTransportClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, PaqetTransport_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaqetTransportServer is the server API for PaqetTransport service.
// All implementations must embed UnimplementedPaqetTransportServer
// for forward compatibility.
//
// PaqetTransport service for bidirectional streaming
type PaqetTransportServer interface {
	// Stream opens a bidirectional stream for data transfer
	Stream(grpc.BidiStreamingServer[StreamData, StreamData]) error
	// Ping tests the connection
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedPaqetTransportServer()
}

// UnimplementedPaqetTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaqetTransportServer struct{}

func (UnimplementedPaqetTransportServer) Stream(grpc.BidiStreamingServer[StreamData, StreamData]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedPaqetTransportServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPaqetTransportServer) mustEmbedUnimplementedPaqetTransportServer() {}
func (UnimplementedPaqetTransportServer) testEmbeddedByValue()                        {}

// UnsafePaqetTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaqetTransportServer will
// result in compilation errors.
type UnsafePaqetTransportServer interface {
	mustEmbedUnimplementedPaqetTransportServer()
}

func RegisterPaqetTransportServer(s grpc.ServiceRegistrar, srv PaqetTransportServer) {
	// If the following call panics, it indicates UnimplementedPaqetTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaqetTransport_ServiceDesc, srv)
}

func _PaqetTransport_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PaqetTransportServer).Stream(&grpc.GenericServerStream[StreamData, StreamData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaqetTransport_StreamServer = grpc.BidiStreamingServer[StreamData, StreamData]

func _PaqetTransport_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaqetTransportServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaqetTransport_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaqetTransportServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaqetTransport_ServiceDesc is the grpc.ServiceDesc for PaqetTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaqetTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paqet.PaqetTransport",
	HandlerType: (*PaqetTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PaqetTransport_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _PaqetTransport_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/tnet/grpc/proto/transport.proto",
}
